### When to use dask.dataframe¶
Pandas is great for tabular datasets that fit in memory. Dask becomes useful when the dataset you want to analyze is larger than your machine's RAM. The demo dataset we're working with is only about 200MB, so that you can download it in a reasonable time, but dask.dataframe will scale to datasets much larger than memory.
Tutorial: https://docs.dask.org/en/latest/

### Requirements
pip3 install aiohttp
python3 -m pip install "dask[dataframe]"

In [11]:
import dask.dataframe as dd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
df = dd.read_csv(url)

In [12]:
df

Dask DataFrame Structure:
                   3       ? alfa-romero     gas     std     two convertible     rwd   front    88.60   168.80    64.10    48.80   2548    dohc    four    130    mpfi    3.47    2.68     9.00     111    5000     21     27   13495
npartitions=1
               int64  object      object  object  object  object      object  object  object  float64  float64  float64  float64  int64  object  object  int64  object  object  object  float64  object  object  int64  int64  object
                 ...     ...         ...     ...     ...     ...         ...     ...     ...      ...      ...      ...      ...    ...     ...     ...    ...     ...     ...     ...      ...     ...     ...    ...    ...     ...
Dask Name: from-delayed, 3 tasks

### Modin is a DataFrame for datasets from 1MB to 1TB+¶
We have focused heavily on bridging the solutions between DataFrames for small data (e.g. pandas) and large data. Often data scientists require different tools for doing the same thing on different sizes of data. The DataFrame solutions that exist for 1MB do not scale to 1TB+, and the overheads of the solutions for 1TB+ are too costly for datasets in the 1KB range. With Modin, because of its light-weight, robust, and scalable nature, you get a fast DataFrame at 1MB and 1TB+.
Tutorial: https://modin.readthedocs.io/en/latest/

### Requirements
pip3 install modin

In [16]:
import modin.pandas as pd
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data'
df = dd.read_csv(url)

In [17]:
df

Dask DataFrame Structure:
                   3       ? alfa-romero     gas     std     two convertible     rwd   front    88.60   168.80    64.10    48.80   2548    dohc    four    130    mpfi    3.47    2.68     9.00     111    5000     21     27   13495
npartitions=1
               int64  object      object  object  object  object      object  object  object  float64  float64  float64  float64  int64  object  object  int64  object  object  object  float64  object  object  int64  int64  object
                 ...     ...         ...     ...     ...     ...         ...     ...     ...      ...      ...      ...      ...    ...     ...     ...    ...     ...     ...     ...      ...     ...     ...    ...    ...     ...
Dask Name: from-delayed, 3 tasks